In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#!pip install numpy

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris_data = load_iris()

In [7]:
iris_data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [13]:
print(iris_data["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [14]:
print(iris_data["target_names"])

['setosa' 'versicolor' 'virginica']


In [15]:
iris_df = pd.DataFrame(data= iris_data["data"], columns=iris_data["feature_names"])

In [16]:
iris_df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [17]:
iris_df["Output"] = iris_data["target"]

In [18]:
iris_df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Output  
0       0  
1       0  
2       0  
3       0  
4       0

In [24]:
X = iris_df[iris_data["feature_names"]].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [25]:
y = iris_df['Output'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
X.shape

(150, 4)

In [68]:
0.20*15000

3000.0

In [19]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [28]:
X_test

array([[5.5, 3.5, 1.3, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [6.1, 2.8, 4.7, 1.2],
       [6.3, 2.3, 4.4, 1.3],
       [4.6, 3.6, 1. , 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [6.3, 3.3, 4.7, 1.6],
       [6. , 2.9, 4.5, 1.5],
       [5.9, 3.2, 4.8, 1.8],
       [4.9, 2.4, 3.3, 1. ],
       [6.7, 2.5, 5.8, 1.8],
       [5. , 2.3, 3.3, 1. ],
       [4.9, 3.6, 1.4, 0.1],
       [6.3, 2.9, 5.6, 1.8],
       [5.4, 3.9, 1.7, 0.4],
       [6.5, 3. , 5.8, 2.2],
       [6.5, 3.2, 5.1, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.8, 2.7, 5.1, 1.9],
       [4.6, 3.1, 1.5, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.3]])

In [30]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2,
       2, 1, 2, 0, 1, 1, 0, 0])

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
knn = KNeighborsClassifier(n_neighbors=2)

In [61]:
knn.fit(X=X_train,y=y_train)

KNeighborsClassifier(n_neighbors=2)

In [62]:
y_est = knn.predict(X_test)

In [63]:
y_test==y_est

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [69]:
knn.score(X_test,y_test)

0.9333333333333333

In [70]:
knn.score(X_train,y_train)

0.975

In [71]:
knn.predict(X_train)==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True])